# Generated by Django 5.2.4 on 2025-08-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('from_city', models.CharField(max_length=200)),
                ('to_city', models.CharField(max_length=200)),
                ('departure', models.TimeField(blank=True, null=True)),
                ('arrival', models.TimeField(blank=True, null=True)),
                ('travel_date', models.DateField(blank=True, null=True)),
                ('bus_type', models.CharField(default='Non-AC', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
