# Generated by Django 5.2.5 on 2025-08-28 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_bus_train'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bus',
        ),
        migrations.DeleteModel(
            name='Train',
        ),
    ]
